# Project information
site_name: DarkLess
site_description: drkless docs
site_author: hand
site_url: https://darkless.cn/my-docs/

# Repository
# repo_name: squidfunk/mkdocs-material
# repo_url: https://github.com/squidfunk/mkdocs-material
# edit_uri: ""

# Copyright
copyright: 'Copyright &copy;2019 darkless'

# Configuration
theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  feature:
    tabs: true
  palette:
    primary: White
    accent: Deep Orange
  font: false
    # text: Roboto
    # code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "book"

# Customization
extra:
  social:
    - type: globe
      link: http://darkless.cn
    - type: github-alt
      link: https://github.com/handbye
    - type: weibo
      link: https://weibo.com/handbye

# Extensions
markdown_extensions:

# Page tree
nav:
  - 首页: index.md
  - DVWA解题:
    - Brute Force: DVWA-Brute-Force.md
    - Command Injection: DVWA-Command-Injection.md
    - CSRF: DVWA-CSRF.md
    - File Inclusion: DVWA-File-Inclusion.md
    - File Upload: DVWA-File-Upload.md
    - SQL Injection: DVWA-sql-injection.md
    - SQL Blind Injection: DVWA-sql-blind-injection.md
    - Weak Session ID: DVWA-Weak Session IDs.md
    - XSS-DOM: DVWA-XSS-DOM.md
    - XSS-Reflected: DVWA-XSS-Reflected.md
    - XSS-Stored: DVWA-XSS-Stored.md
  - XCTF初级wp:
    - XCTF-primary-writeUp: XCTF-primary-writeup.md
    - view_source: XCTF-web-view_source.md
    - get_post: XCTF-web-get_post.md
    - robots: XCTF-web-robots.md
    - backup: XCTF-web-backup.md
    - cookie: XCTF-web-cookie.md
    - disable_buttom: XCTF-web-disable_buttom.md
    - simple_js: XCTF-web-simplejs.md
    - xff_refer: XCTF-web-xff_refer.md
    - weak_auth: XCTF-web-weak_auth.md
    - webshell: XCTF-web-webshell.md
    - command_execution: XCTF-web-command_execution.md
    - simple_php: XCTF-web-simple_php.md
  - XCTF高级wp:
    - XCTF-challenge-writeUp: XCTF-challenge-writeup.md
    - Cat: XCTF-web-Cat.md
    - ics-06: XCTF-web-ics-06.md
    - NewsCenter: XCTF-web-NewsCenter.md
    - mfw: XCTF-web-mfw.md
    - NaNNaNNaNNaN-Batman: XCTF-web-NaNNaNNaNNaN-Batman.md
    - upload: XCTF-web-upload.md
    - PHP2: XCTF-web-PHP2.md
    - unserialize3: XCTF-web-unserialize3.md
    - ics-05: XCTF-web-ics-05.md

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto